name: Echo Secrets Example

on:
  workflow_dispatch:

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a secret
        run: echo "The secret value is ${{ secrets.REACT_APP_BASE_URL }}"
      
      - name: Mask and echo a secret
        run: |
          echo "::add-mask::${{ secrets.REACT_APP_BASE_URL }}"
          echo "The masked secret value is ${{ secrets.REACT_APP_BASE_URL }}"
